#!/usr/bin/env python3.5
import threading
import J1708Driver
import struct
import time
import socket

dpa_mid = None
ecm_mid = None

logging_socket = socket.socket(family=socket.AF_INET,type=socket.SOCK_DGRAM)
logging_socket.bind(('localhost',13373))

class PassThread(threading.Thread):
    def __init__(self,inport,outport,name):#name is either "ECM" or "DPA"
        super(PassThread,self).__init__()
        self.inport = inport
        self.outport = outport
        self.name = name


    def apply_filter(self,message):
        return [message]

    

    def run(self):
        while True:
            msg = self.inport.read_message(checksum=True)
            if msg is not None and len(msg) > 0:
                self.outport.send_message(msg,has_check=True)
                proto = "J1708"
                sr = "RM" if self.name == "ECM" else "SM"
                data = ",".join(list(map(lambda x: "%x" % x,msg)))
                to_send = bytes(','.join([proto,sr,data]),"ascii")
                logging_socket.sendto(to_send,('localhost',13371))

    



if __name__ == '__main__':
    ecmdriver = J1708Driver.J1708Driver(J1708Driver.ECM)
    dpadriver = J1708Driver.J1708Driver(J1708Driver.DPA)
    threads = []
    threads.append(PassThread(ecmdriver,dpadriver,"ECM"))
    threads.append(PassThread(dpadriver,ecmdriver,"DPA"))
    list(map(lambda x: x.start(),threads))
    list(map(lambda x: x.join(), threads))

    
